---
- name: Install OpenHPC master SLURM packages
  yum:
    name:
      - "@ohpc-slurm-server"
      - "slurm-slurmctld-ohpc"
      - "slurm-example-configs-ohpc"
    state: present

- name: Select the SLURM service to control
  set_fact:
    openhpc_slurm_service: slurmctld

- name: Install OpenHPC LMOD
  yum:
    name: "lmod-ohpc"
    state: present
    