---

- include_tasks: pre.yml

- name: Ensure OpenHPC repos
  ansible.builtin.yum_repository: "{{ item }}" # noqa: args[module]
  loop: "{{ ohpc_openhpc_repos[ansible_distribution_major_version] }}"
  loop_control:
    label: "{{ item.name }}"

- name: Ensure extra repos
  ansible.builtin.yum_repository: "{{ item }}" # noqa: args[module]
  loop: "{{ openhpc_extra_repos }}"
  loop_control:
    label: "{{ item.name }}"

- name: Enable PowerTools repo
  # NB: doesn't run command  `dnf config-manager --set-enabled PowerTools` as can't make that idempotent
  lineinfile:
    path: /etc/yum.repos.d/Rocky-PowerTools.repo
    create: false # raises error if not already installed
    regexp: enabled=
    line: enabled=1

- name: Build host-specific list of required slurm packages
  set_fact:
    openhpc_slurm_pkglist: "{{ openhpc_slurm_pkglist | default([]) + item.value }}"
  loop: "{{ ohpc_slurm_packages | dict2items }}"
  when: (openhpc_enable.get(item.key, false)) or ()

- name: Install required slurm packages
  yum:
    name: "{{ openhpc_slurm_pkglist | reject('eq', '') }}"
  when: openhpc_slurm_pkglist | default(false, true)

- name: Install packages from openhpc_packages variable
  yum:
    name: "{{ openhpc_packages }}"

...
